## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
git:
  depth: 99999999
addons:
  apt:
    packages:
      - gfortran
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew install gcc;
    fi ;
## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("OrdinaryDiffEqExtendedTests"); Pkg.test("OrdinaryDiffEqExtendedTests"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("OrdinaryDiffEqExtendedTests")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("OrdinaryDiffEqExtendedTests")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
